# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller py2app
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pytest
    - name: Create setup.py for py2app
      run: |
        echo "from setuptools import setup
        
        APP = ['main.py']
        DATA_FILES = []
        OPTIONS = {
            'argv_emulation': True,
            'packages': ['pytesseract', 'PIL'],
        }
        
        setup(
        app=APP,
        data_files=DATA_FILES,
        options={'py2app': OPTIONS},
        setup_requires=['py2app'],
        )" > setup.py

    - name: Built application with py2app
      run: |
        python setup.py py2app

    - name: Move application bundle to root directory
      run: |
        mv dist/main.app .

    - name: Commit and push application bundle |
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add main.app
        git commit -m "Built application bundle"
        git remote set-url origin https://${{ secrets.BCM_PAT }}@github.com/johnnynalley/businessCardManager.git
        git push origin main
